#!/bin/bash
# Copyright(c)2014 NTT corp. All Rights Reserved.
# DB1-1-1-1_1

. ./common

S3USER=test1

_s3_put /bucket -H "x-amz-grant-read: id='${TEST1_TENANT}:${TEST1_USER}'" \
    -H "x-amz-grant-read: id='${TEST2_TENANT}:${TEST2_USER}'"

_s3_get /bucket?acl -D - | _filter_curl xml
