#!/bin/bash
# Copyright(c)2014 NTT corp. All Rights Reserved.
# DB1-1-2-4_7

. ./common

S3USER=test1

_s3_put /bucket
_s3_get /bucket?acl -D - | _filter_curl xml

S3USER=test2
_s3_get /bucket?acl -D - | _filter_curl xml

S3USER=test1

_s3_put /bucket?acl -H "x-amz-grant-read-acp: id='${TEST1_TENANT}:${TEST1_USER},id='${TEST2_TENANT}:${TEST2_USER}'"
_s3_get /bucket?acl -D - | _filter_curl xml

S3USER=test2

_s3_get /bucket?acl -D - | _filter_curl xml
