#!/bin/bash
# Copyright(c)2014 NTT corp. All Rights Reserved.
# DB1-1-3-2_5

. ./common

S3USER=test1
MD5=$(_md5 ./066_dir/lifecycle_Date_Days.xml)

_s3_put /bucket
_s3_put /bucket?lifecycle -T ./066_dir/lifecycle_Date_Days.xml
_s3_get /bucket?lifecycle -D - | _filter_curl xml


MD5=$(_md5 ./066_dir/lifecycle_noDate.xml)
_s3_put /bucket?lifecycle -T ./066_dir/lifecycle_noDate.xml
_s3_get /bucket?lifecycle -D - | _filter_curl xml

