#!/bin/bash
# Copyright(c)2014 NTT corp. All Rights Reserved.
# DB1-1-3-3_3

. ./common

S3USER=test1
MD5=$(_md5 ./070_dir/lifecycle_Days.xml)

_s3_put /bucket
_s3_put /bucket?lifecycle -T ./070_dir/lifecycle_Days.xml
_s3_delete /bucket?lifecycle
_s3_get /bucket?lifecycle -D - | _filter_curl xml
