#!/bin/bash
# Copyright(c)2014 NTT corp. All Rights Reserved.
# DB1-1-3-3_1

. ./common

S3USER=test1

_sw_put /a+b
_s3_delete /a+b?lifecycle -D - | _filter_curl xml

_sw_put /a*b
_s3_delete /a*b?lifecycle -D - | _filter_curl xml

