#!/bin/bash
# Copyright(c)2014 NTT corp. All Rights Reserved.
# DB1-1-6-1_4

. ./common

S3USER=test1

_s3_put /bucket
_s3_put /bucket_log
_s3_put /bucket_log2
_s3_put /bucket_log?acl -H 'x-amz-grant-read-acp: uri="http://acs.amazonaws.com/groups/s3/LogDelivery"' -H 'x-amz-grant-write: uri="http://acs.amazonaws.com/groups/s3/LogDelivery"'
_s3_put /bucket_log2?acl -H 'x-amz-grant-read-acp: uri="http://acs.amazonaws.com/groups/s3/LogDelivery"' -H 'x-amz-grant-write: uri="http://acs.amazonaws.com/groups/s3/LogDelivery"'
_s3_put /bucket?logging -T ./080_dir/logging1.xml -D - | _filter_curl xml
_s3_get /bucket?logging -D - | _filter_curl xml
