#!/bin/bash
# Copyright(c)2014 NTT corp. All Rights Reserved.
# DB1-1-5-1_3

. ./common

S3USER=test1

_s3_put /bucket
_s3_put /bucket?versioning -T ./087_dir/testVersioning-Enabled
_s3_get /bucket?versioning -D - | _filter_curl xml
_s3_put /bucket?versioning -T ./087_dir/testVersioning-Suspended
_s3_get /bucket?versioning -D - | _filter_curl xml
