#!/bin/bash
# Copyright(c)2014 NTT corp. All Rights Reserved.
# DB1-1-5-3_5

. ./common

S3USER=test1

_s3_put /bucket
_s3_put /bucket?versioning -T ./095_dir/testVersioning-Enabled
_s3_put /bucket/obj -T /dev/null
_s3_delete /bucket/obj
_s3_get /bucket?versions -D - | _filter_curl xml
