#!/bin/bash
# Copyright(c)2014 NTT corp. All Rights Reserved.
# DB1-1-2-2_3

. ./common

S3USER=test1

_s3_put /bucket -H "x-amz-grant-full-control: id='${TEST1_TENANT}:${TEST1_USER},id='${TEST2_TENANT}:${TEST2_USER}',id='${TEST3_TENANT}:${TEST3_USER}'"
_s3_get /bucket -D - | _filter_curl xml

S3USER=test2

echo data > $tmp.data
MD5=$(_md5 $tmp.data) CONTENT_TYPE='application/octet-stream' \
    _s3_put /bucket/objectA -T $tmp.data \
    -H 'Content-Disposition: attachment; filename="a.txt.gz"' \
    -H 'Content-Encoding: gzip' \
    -H "Content-Length: $(_file_size $tmp.data)" \
    -H 'Expect: 100-continue' \
    -H 'x-amz-storage-class: STANDARD' \
    -H "x-amz-grant-full-control: id='${TEST3_TENANT}:${TEST3_USER}" -D - | _filter_curl
_s3_get /bucket/objectA?acl -D - | _filter_curl xml

S3USER=test3

_s3_put /bucket/objectA?acl -H "x-amz-grant-read: uri='http://acs.amazonaws.com/groups/global/AllUsers'"

S3USER=test2

_s3_get /bucket/objectA?acl -D - | _filter_curl xml
