#!/bin/bash
# Copyright(c)2014 NTT corp. All Rights Reserved.
# DB1-1-4-10_11

. ./common

S3USER=test1

_s3_put /bucket -D - | _filter_curl
_s3_get /bucket -D - | _filter_curl xml
_s3_get /bucket/object -D - | _filter_curl xml
