#!/bin/bash
# Copyright(c)2014 NTT corp. All Rights Reserved.
# DB1-1-1-4-13_7

. ./common

S3USER=test1

_s3_put /hoge
_s3_get /hoge?versioning | _filter_curl xml
_s3_get /hoge?lifecycle | _filter_curl xml

echo data > $tmp.data
MD5=$(_md5 $tmp.data) CONTENT_TYPE='application/octet-stream' \
    _s3_put /hoge/a -T $tmp.data \
    -H 'Content-Disposition: attachment; filename="a.txt.gz"' \
    -H 'Content-Encoding: gzip' \
    -H "Content-Length: $(_file_size $tmp.data)" \
    -H 'x-amz-storage-class: STANDARD' \
    -H "x-amz-meta-hoge: 1" -D - | _filter_curl

_s3_head /hoge/a | _filter_curl
