#!/bin/bash
# Copyright(c)2014 NTT corp. All Rights Reserved.
# DB1-1-1-4-11_5

. ./common

S3USER=test1

_s3_put /containerA
_s3_get /containerA?versioning | _filter_curl xml
_s3_get /containerA?lifecycle | _filter_curl xml

echo data > $tmp.data
MD5=$(_md5 $tmp.data) CONTENT_TYPE='application/octet-stream' \
    _s3_put /containerA/objectA -T $tmp.data \
    -H 'Content-Disposition: attachment; filename="a.txt.gz"' \
    -H 'Content-Encoding: gzip' \
    -H "Content-Length: $(_file_size $tmp.data)" \
    -H 'Expect: 100-continue' \
    -H "x-amz-grant-read: id="$TEST1_TENANT":"$TEST1_USER"" -D - | _filter_curl

_s3_get /containerA/objectA?acl -D - | _filter_curl xml

_s3_delete /containerA/objectA

_s3_get /containerA/objectA -D - | _filter_curl xml
