#!/bin/bash
# Copyright(c)2014 NTT corp. All Rights Reserved.
# DB1-1-4-12_24

. ./common

num=2

S3USER=test1

_gen_delete_xml()
{
    echo '<Delete>'
    echo '<Quiet>true</Quiet>'

    for i in `seq $num`; do
	echo "<Object><Key>object$i</Key></Object>"
    done

    echo '</Delete>'
}

_gen_delete_xml > $tmp.delete.xml
cat $tmp.delete.xml

_s3_put /bucket
_s3_put /bucket/object1 -T /dev/null
MD5=$(_md5 $tmp.delete.xml) _s3_post /bucket?delete -T $tmp.delete.xml -D - | _filter_curl xml
_s3_get /bucket/ | _filter_curl xml
