#!/bin/bash
# Copyright(c)2014 NTT corp. All Rights Reserved.
# DB1-1-4-12_4

. ./common

S3USER=test1

_s3_put /bucket
_s3_put /bucket/object1 -T /dev/null
_s3_put /bucket/object2 -T /dev/null

_gen_delete_xml()
{
    echo '<DELETE>'
    echo '<Quiet>false</Quiet>'
    echo "<Object><Key>obj</Key><VersionId></VersionId></Object>"
    echo '</DELETE>'
}

_gen_delete_xml > $tmp.delete.xml
cat $tmp.delete.xml

MD5=$(_md5 $tmp.delete.xml) _s3_post /bucket?delete -T $tmp.delete.xml -D - | _filter_curl xml
_s3_get /bucket | _filter_curl xml


_gen_delete_xml()
{
    echo '<Delete>'
    echo '<QUIET>false</QUIET>'
    echo "<Object><Key>obj</Key><VersionId></VersionId></Object>"
    echo '</Delete>'
}

_gen_delete_xml > $tmp.delete.xml
cat $tmp.delete.xml

MD5=$(_md5 $tmp.delete.xml) _s3_post /bucket?delete -T $tmp.delete.xml -D - | _filter_curl xml
_s3_get /bucket | _filter_curl xml


_gen_delete_xml()
{
    echo '<Delete>'
    echo '<Quiet>false</Quiet>'
    echo "<OBJECT><Key>obj</Key><VersionId></VersionId></OBJECT>"
    echo '</Delete>'
}

_gen_delete_xml > $tmp.delete.xml
cat $tmp.delete.xml

MD5=$(_md5 $tmp.delete.xml) _s3_post /bucket?delete -T $tmp.delete.xml -D - | _filter_curl xml
_s3_get /bucket | _filter_curl xml


_gen_delete_xml()
{
    echo '<Delete>'
    echo '<Quiet>false</Quiet>'
    echo "<KEY>obj</KEY><VersionId></VersionId>"
    echo '</Delete>'
}

_gen_delete_xml > $tmp.delete.xml
cat $tmp.delete.xml

MD5=$(_md5 $tmp.delete.xml) _s3_post /bucket?delete -T $tmp.delete.xml -D - | _filter_curl xml
_s3_get /bucket | _filter_curl xml

_gen_delete_xml()
{
    echo '<Delete>'
    echo '<Quiet>false</Quiet>'
    echo "<Key>obj</Key><VERSIONID></VERSIONID>"
    echo '</Delete>'
}

_gen_delete_xml > $tmp.delete.xml
cat $tmp.delete.xml

MD5=$(_md5 $tmp.delete.xml) _s3_post /bucket?delete -T $tmp.delete.xml -D - | _filter_curl xml
_s3_get /bucket | _filter_curl xml
