#!/bin/bash
# Copyright(c)2014 NTT corp. All Rights Reserved.
# DB1-1-7-1_1

. ./common

num=10

S3USER=test1

_gen_complete_xml()
{
    echo '<CompleteMultipartUpload>'

    for i in `seq $num`; do
        j=$(($i - 1))
        echo '<Part>'
        echo "<PartNumber>$i</PartNumber>"
        echo "<ETag>$(_etag ./data/segment_50M.dat_0$j)</ETag>"
        echo '</Part>'
    done

    echo '</CompleteMultipartUpload>'
}


_s3_put /130

upload_id=$(_s3_post /130/object?uploads \
    -H "x-amz-acl: public-read-write" \
    -H "x-amz-meta-hoge1: 1" \
    -H "x-amz-meta-hoge2: 2" \
    -H "x-amz-meta-hoge3: 3" | \
    _xq /InitiateMultipartUploadResult/UploadId)

for i in `seq $num`; do
    j=$(($i - 1))
    _s3_put /130/object?uploadId=${upload_id}\&partNumber=$i \
        -T ./data/segment_50M.dat_0$j
done

_gen_complete_xml > 130.complete.xml

_s3_post /130/object?uploadId=${upload_id} -T 130.complete.xml -D - | \
    _filter_curl xml

_s3_head /130/object | _filter_curl

_s3_get /130/object?acl -D - | _filter_curl xml

rm 130.complete.xml

