#!/bin/bash
# Copyright(c)2014 NTT corp. All Rights Reserved.
# DB1-1-8-3_1

. ./common

num=10

S3USER=test1

_gen_complete_xml()
{
    echo '<CompleteMultipartUpload>'

    for i in `seq $num`; do
        j=$(($i - 1))
        echo '<Part>'
        echo "<PartNumber>$i</PartNumber>"
        echo "<ETag>$(_etag ./data/segment_50M.dat_0$j)</ETag>"
        echo '</Part>'
    done

    echo '</CompleteMultipartUpload>'
}


_s3_put /138

upload_id=$(_s3_post /138/object?uploads \
    -H "x-amz-acl: public-read-write" \
    -H "x-amz-meta-hoge1: 1" \
    -H "x-amz-meta-hoge2: 2" \
    -H "x-amz-meta-hoge3: 3" | \
    _xq /InitiateMultipartUploadResult/UploadId)

for i in `seq $num`; do
    j=$(($i - 1))
    _s3_put /138/object?uploadId=${upload_id}\&partNumber=$i \
        -T ./data/segment_50M.dat_0$j
done

_gen_complete_xml > 138.complete.xml

_s3_post /138/object?uploadId=${upload_id} -T 138.complete.xml -D - | \
    _filter_curl xml

rm 138.complete.xml



upload_id=$(_s3_post /138/object2?uploads \
    -H "x-amz-acl: public-read" \
    -H "x-amz-meta-hoge4: 4" \
    -H "x-amz-meta-hoge5: 5" \
    -H "x-amz-meta-hoge6: 6" | \
    _xq /InitiateMultipartUploadResult/UploadId)

_s3_put /138/object2?uploadId=${upload_id}\&partNumber=1 -H "x-amz-copy-source: /138/object" -H "x-amz-copy-source-range: byte=0-5242879" | _filter_curl xml


_sw_get /138+segments | _filter_curl | sed -e "s/${upload_id}/UPLOAD_ID/g" | grep object2

