#!/bin/bash
# Copyright(c)2014 NTT corp. All Rights Reserved.
# DB1-1-8-3_8

. ./common


S3USER=test1

etag=$(_etag ./data/segment_50M.dat_01)


_s3_put /139

_s3_put /139/object -T ./data/segment_50M.dat_01


upload_id=$(_s3_post /139/object2?uploads | \
    _xq /InitiateMultipartUploadResult/UploadId)

_s3_put /139/object2?uploadId=${upload_id}\&partNumber=1 \
    -H "x-amz-copy-source: /139/object" \
    -H "x-amz-copy-source-range: byte=0-1000000" \
    -H "x-amz-copy-source-if-match: $etag" | _filter_curl xml


_sw_get /139+segments | _filter_curl | sed -e "s/${upload_id}/UPLOAD_ID/g" | grep object2

