#!/bin/bash
# Copyright(c)2014 NTT corp. All Rights Reserved.
# DB1-1-8-3_11

. ./common


S3USER=test1


_s3_put /141

_s3_put /141/object -T ./data/segment_50M.dat_01


upload_id=$(_s3_post /141/object2?uploads | \
    _xq /InitiateMultipartUploadResult/UploadId)

_s3_put /141/object2?uploadId=${upload_id}\&partNumber=1 \
    -H "x-amz-copy-source: /141/object" \
    -H "x-amz-copy-source-if-modified-since: Wed, 1 Jan 3000 00:00:00 GMT" | _filter_curl xml

_sw_get /141+segments | _filter_curl

