#!/bin/bash
# Copyright(c)2014 NTT corp. All Rights Reserved.
# DB1-1-8-5_2

. ./common

num=10

S3USER=test1


_s3_put /148

upload_id=$(_s3_post /148/object?uploads | \
    _xq /InitiateMultipartUploadResult/UploadId)

for i in `seq $num`; do
    j=$(($i - 1))
    _s3_put /148/object?uploadId=${upload_id}\&partNumber=$i \
        -T ./data/segment_1M.dat_0$j
done

_sw_get /148+segments | grep object/${upload_id} | wc -l

_s3_delete /148/object?uploadId=hoge -D - | _filter_curl xml

_sw_get /148/object -D - | _filter_curl

_sw_get /148+segments | grep object/${upload_id} | wc -l

