#!/bin/bash
# Copyright(c)2014 NTT corp. All Rights Reserved.
# DB1-1-8-6_1

. ./common

num=10

S3USER=test1


_s3_put /150

upload_id=$(_s3_post /150/object?uploads | \
    _xq /InitiateMultipartUploadResult/UploadId)

for i in `seq $num`; do
    j=$(($i - 1))
    _s3_put /150/object?uploadId=${upload_id}\&partNumber=$i \
        -T ./data/segment_1M.dat_0$j
done

_s3_get /150/object?uploadId=${upload_id} | _filter_curl xml

_sw_get /150+segments | grep object/${upload_id} | wc -l

