#!/bin/bash
# Copyright(c)2014 NTT corp. All Rights Reserved.
# DB1-1-8-6_3

. ./common

num=4

S3USER=test1


_s3_put /151

upload_id=$(_s3_post /151/%e3%81%82%2etxt?uploads | \
    _xq /InitiateMultipartUploadResult/UploadId)

for i in `seq $num`; do
    j=$(($i - 1))
    _s3_put /151/%e3%81%82%2etxt?uploadId=${upload_id}\&partNumber=$i \
        -T ./data/segment_1M.dat_0$j
done

_s3_get /151/%e3%81%82%2etxt?uploadId=${upload_id}\&encoding-type=url\&max-parts=4\&part-number-marker=2 \
    -D - | _filter_curl xml

_sw_get /151+segments | grep ${upload_id} | wc -l

