#!/bin/bash
# Copyright(c)2014 NTT corp. All Rights Reserved.
# DB1-1-8-6_4

. ./common

num=4

S3USER=test1


_s3_put /152

upload_id=$(_s3_post /152/%e3%81%82%2etxt?uploads | \
    _xq /InitiateMultipartUploadResult/UploadId)

for i in `seq $num`; do
    j=$(($i - 1))
    _s3_put /152/%e3%81%82%2etxt?uploadId=${upload_id}\&partNumber=$i \
        -T ./data/segment_1M.dat_0$j
done

_s3_get /152/%e3%81%82%2etxt?uploadId=hoge -D - | _filter_curl xml

