#!/bin/bash
# Copyright(c)2014 NTT corp. All Rights Reserved.
# DB1-1-8-7_9

. ./common


S3USER=test1

_s3_put /157

upload_id=$(_s3_post /157/%e3%81%82%2etxt?uploads _xq /InitiateMultipartUploadResult/UploadId)
upload_id=$(_s3_post /157/%e3%81%84%2etxt?uploads _xq /InitiateMultipartUploadResult/UploadId)
upload_id=$(_s3_post /157/object?uploads _xq /InitiateMultipartUploadResult/UploadId)


S3USER=test2

_s3_get /157?uploads -D - | _filter_curl xml

