#!/bin/bash
# Copyright(c)2014 NTT corp. All Rights Reserved.
# DB1-1-4-10_22

. ./common
S3USER=test1

echo '<LifecycleConfiguration>
  <Rule>
    <ID>Rule-1</ID>
    <Prefix>a</Prefix>
    <Status>Enabled</Status>
    <Expiration>
      <Date>2014-05-20T00:00:00.000Z</Date>
    </Expiration>
  </Rule>
</LifecycleConfiguration>' > $tmp.lifecycle_Date.xml

_s3_put /bucket
MD5=$(_md5 $tmp.lifecycle_Date.xml) _s3_put /bucket?lifecycle -T $tmp.lifecycle_Date.xml
_s3_get /bucket?lifecycle -D - | _filter_curl xml
_s3_put /bucket/aobj -T /dev/null
_s3_get /bucket/aobj -D - | _filter_curl xml
