#!/bin/bash
# Copyright(c)2014 NTT corp. All Rights Reserved.
# GET Object to Bucket that set versioning and expier.

. ./common
S3USER=test1

echo '<LifecycleConfiguration>
  <Rule>
    <ID>Rule-1</ID>
    <Prefix>a</Prefix>
    <Status>Enabled</Status>
    <Expiration>
      <Date>2014-05-20T00:00:00.000Z</Date>
    </Expiration>
  </Rule>
</LifecycleConfiguration>' > $tmp.lifecycle_Date.xml

echo '<VersioningConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
<Status>Enabled</Status>
</VersioningConfiguration>' > $tmp.versioning.xml

_s3_put /bucket
_s3_put /bucket?versioning -T $tmp.versioning.xml
_s3_get /bucket?versioning -D - | _filter_curl xml

MD5=$(_md5 $tmp.lifecycle_Date.xml) _s3_put /bucket?lifecycle -T $tmp.lifecycle_Date.xml -D - | _filter_curl xml
_s3_get /bucket?lifecycle -D - | _filter_curl xml
version_id=$(_s3_put /bucket/aobj -T /dev/null -D - | _hq 'x-amz-version-id')
_s3_get /bucket/aobj?versionId=${version_id} -D - | _filter_curl
