#!/bin/bash
# Copyright(c)2014 NTT corp. All Rights Reserved.
# DB1-1-4-1_3

. ./common
S3USER=test1
_s3_put /bucket

S3USER=test2
_s3_put /bucket2

S3USER=test1
_s3_get / -H "hoge: hoge" -D - | _filter_curl xml
