#!/bin/bash

# PUT Bucket

. ./common

echo '
<CreateBucketConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
<LocationConstraint>US</LocationConstraint>
</CreateBucketConfiguration>' > $tmp.default.xml

echo '
<CreateBucketConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
<LocationConstraint>us-west-2</LocationConstraint>
</CreateBucketConfiguration>' > $tmp.us_west_2.xml

S3USER=tester

_s3_put /bucket -D - -T $tmp.default.xml | _filter_curl
_s3_put /bucket -D - -T $tmp.us_west_2.xml | _filter_curl xml
