#!/bin/bash

# PUT Bucket ACL

. ./common

S3USER=tester

_s3_put /bucket -H 'x-amz-acl: authenticated-read'
_s3_put /bucket/object -T /dev/null
_s3_get /bucket -D - | _filter_curl xml

S3USER=tester2
_s3_get /bucket -D - | _filter_curl xml
