#!/bin/bash

# GET Bucket ACL

. ./common

S3USER=tester

_s3_put /bucket -H "x-amz-grant-read: id='${TENANT}:${TESTER_USER}'" \
    -H "x-amz-grant-read: id='${TENANT}:${TESTER2_USER}'"

_s3_get /bucket?acl -D - | _filter_curl xml

S3USER=tester2
_s3_get /bucket?acl -D - | _filter_curl xml

S3USER=tester
_s3_put /bucket?acl -H "x-amz-grant-full-control: id='${TENANT}:${TESTER_USER}'" \
    -H "x-amz-grant-full-control: id='${TENANT}:${TESTER2_USER}'"

_s3_get /bucket?acl -D - | _filter_curl xml

S3USER=tester2
_s3_get /bucket?acl -D - | _filter_curl xml
