#!/bin/bash

# DELETE Bucket lifecycle

. ./common

S3USER=tester

_s3_put /bucket

echo '<LifecycleConfiguration>
<Rule>
   <ID>Archive and then delete rule</ID>
   <Prefix>prefix_</Prefix>
   <Status>Enabled</Status>
   <Expiration><Days>0</Days></Expiration>
</Rule>
</LifecycleConfiguration>' > $tmp.lifecycle.xml
MD5=$(_md5 $tmp.lifecycle.xml) _s3_put /bucket?lifecycle -T $tmp.lifecycle.xml

_s3_delete /bucket?lifecycle -D - | _filter_curl
