#!/bin/bash

# GET Bucket Object versions

. ./common

S3USER=tester

echo '<VersioningConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/"> 
<Status>Enabled</Status>
</VersioningConfiguration>' > $tmp.versioning.xml

_s3_put /bucket
_s3_put /bucket?versioning -T $tmp.versioning.xml

_s3_put /bucket/object -T /dev/null -D -  | _filter_curl
_s3_delete /bucket/object -D -  | _filter_curl

_s3_get /bucket?versions -D - | _filter_curl xml
