#!/bin/bash

# GET Bucket versioning

. ./common

S3USER=tester

echo '<VersioningConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/"> 
<Status>Enabled</Status>
</VersioningConfiguration>' > $tmp.versioning.xml

_s3_put /bucket
_s3_put /bucket?versioning -T $tmp.versioning.xml

_s3_get /bucket?versioning -D -  | _filter_curl xml
