#!/bin/bash

# object expirer

. ./common

echo '<LifecycleConfiguration>
<Rule>
   <ID>delete rule</ID>
   <Prefix/>
   <Status>Enabled</Status>
   <Expiration><Days>0</Days></Expiration>
</Rule>
</LifecycleConfiguration>' > $tmp.lifecycle.xml

S3USER=tester

_s3_put /bucket
MD5=$(_md5 $tmp.lifecycle.xml) _s3_put /bucket?lifecycle -T $tmp.lifecycle.xml

_s3_put /bucket/object -T /dev/null
_s3_get /bucket/object -D - | _filter_curl
