#!/bin/bash

# Bucket versioning

. ./common

num=4

S3USER=tester

_s3_put /bucket

echo '<VersioningConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/"> 
<Status>Enabled</Status>
</VersioningConfiguration>' > $tmp.versioning.xml
_s3_put /bucket?versioning -T $tmp.versioning.xml

for i in `seq $num`; do
    echo $i > $tmp.data.$i
    version_id[$i]=$(_s3_put /bucket/object -T $tmp.data.$i -D - | \
	_hq 'x-amz-version-id')
done

for i in `seq $num`; do
    _s3_get /bucket/object?versionId=${version_id[$i]} -D - | _filter_curl
done
