#!/bin/bash
# Copyright(c)2014 NTT corp. All Rights Reserved.
# DB1-1-2-1_8

. ./common

S3USER=tester

_s3_put /bucket -H "x-amz-acl:privat" | _filter_curl xml

_s3_get /bucket -D - | _filter_curl xml

