#!/bin/bash
# Copyright(c)2014 NTT corp. All Rights Reserved.
# DB1-1-2-1_2

. ./common

S3USER=tester

_s3_put /bucket -H "x-amz-grant-full-control: id='${TENANT}:${TESTER2_USER}'"
_s3_get /bucket?acl -D - | _filter_curl xml

S3USER=tester2

_s3_put /bucket?acl -H "x-amz-acl:log-delivery-write"
_s3_get /bucket?acl -D - | _filter_curl xml

S3USER=tester

_s3_put /bucket?acl -H "x-amz-acl:log-delivery-write"
_s3_get /bucket?acl -D - | _filter_curl xml

