#!/bin/bash
# Copyright(c)2014 NTT corp. All Rights Reserved.
# DB1-1-2-1_9

. ./common

S3USER=tester

_s3_put /bucket -H "x-amz-acl:public-read"
_s3_get /bucket?acl -D - | _filter_curl xml

_s3_put /bucket?acl -H "x-amz-acl:PRIVATE" | _filter_curl xml
_s3_get /bucket?acl -D - | _filter_curl xml
