#!/bin/bash
# Copyright(c)2014 NTT corp. All Rights Reserved.
# DB1-1-2-4_7

. ./common

S3USER=tester

_s3_put /bucket
_s3_get /bucket?acl -D - | _filter_curl xml

S3USER=tester2
_s3_get /bucket?acl -D - | _filter_curl xml

S3USER=tester

_s3_put /bucket?acl -H "x-amz-grant-read-acp: id='${TENANT}:${TESTER_USER},id='${TENANT}:${TESTER2_USER}'"
_s3_get /bucket?acl -D - | _filter_curl xml

S3USER=tester2

_s3_get /bucket?acl -D - | _filter_curl xml
