#!/bin/bash
# Copyright(c)2014 NTT corp. All Rights Reserved.
# DB1-1-3-1_13

. ./common

echo '<LifecycleConfiguration>
  <Rule>
    <ID>Rule-1</ID>
    <Prefix>a</Prefix>
    <Status>Enabled</Status>
    <Expiration>
      <Days>10</Days>
    </Expiration>
  </Rule>
</LifecycleConfiguration>' > $tmp.lifecycle.days.xml

echo '<LifecycleConfiguration>
  <Rule>
    <ID>Rule-1</ID>
    <Prefix>a</Prefix>
    <Status>Enabled</Status>
    <Expiration>
      <Date>2014-05-20T00:00:00.000Z</Date>
    </Expiration>
  </Rule>
</LifecycleConfiguration>' > $tmp.lifecycle.date.xml

S3USER=tester

_s3_put /bucket
MD5=$(_md5 $tmp.lifecycle.days.xml) _s3_put /bucket?lifecycle -T $tmp.lifecycle.days.xml
_s3_get /bucket?lifecycle -D - | _filter_curl xml


MD5=$(_md5 $tmp.lifecycle.date.xml) _s3_put /bucket?lifecycle -T $tmp.lifecycle.date.xml
_s3_get /bucket?lifecycle -D - | _filter_curl xml

