#!/bin/bash
# Copyright(c)2014 NTT corp. All Rights Reserved.
# DB1-1-3-3_3

. ./common

echo '<LifecycleConfiguration>
  <Rule>
    <ID>Rule-1</ID>
    <Prefix>a</Prefix>
    <Status>Enabled</Status>
    <Expiration>
      <Days>10</Days>
    </Expiration>
  </Rule>
</LifecycleConfiguration>' > $tmp.lifecycle.xml

S3USER=tester

_s3_put /bucket
MD5=$(_md5 $tmp.lifecycle.xml) _s3_put /bucket?lifecycle -T $tmp.lifecycle.xml
_s3_delete /bucket?lifecycle
_s3_get /bucket?lifecycle -D - | _filter_curl xml
