#!/bin/bash
# Copyright(c)2014 NTT corp. All Rights Reserved.
# DB1-1-6-1_4

. ./common

echo '<BucketLoggingStatus xmlns="http://doc.s3.amazonaws.com/2006-03-01">
  <LoggingEnabled>
    <TargetBucket>bucket_log</TargetBucket>
    <TargetBucket>bucket_log2</TargetBucket>
    <TargetPrefix>logs_</TargetPrefix>
    <TargetGrants>
      <Grant>
        <Grantee xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="Group">
          <URI>http://acs.amazonaws.com/groups/global/AuthenticatedUsers</URI>
        </Grantee>
        <Permission>READ</Permission>
      </Grant>
      <Grant>
        <Grantee xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="CanonicalUser">
          <ID>demo:demo</ID>
          <DisplayName>demo:demo</DisplayName>
        </Grantee>
        <Permission>READ</Permission>
      </Grant>
    </TargetGrants>
  </LoggingEnabled>
</BucketLoggingStatus>' > $tmp.logging.xml

S3USER=tester

_s3_put /bucket
_s3_put /bucket_log
_s3_put /bucket_log2
_s3_put /bucket_log?acl -H 'x-amz-grant-read-acp: uri="http://acs.amazonaws.com/groups/s3/LogDelivery"' -H 'x-amz-grant-write: uri="http://acs.amazonaws.com/groups/s3/LogDelivery"'
_s3_put /bucket_log2?acl -H 'x-amz-grant-read-acp: uri="http://acs.amazonaws.com/groups/s3/LogDelivery"' -H 'x-amz-grant-write: uri="http://acs.amazonaws.com/groups/s3/LogDelivery"'
_s3_put /bucket?logging -T $tmp.logging.xml -D - | _filter_curl xml
_s3_get /bucket?logging -D - | _filter_curl xml
