#!/bin/bash
# Copyright(c)2014 NTT corp. All Rights Reserved.
# DB1-1-5-1_3

. ./common

echo '<VersioningConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
   <Status>Enabled</Status>
</VersioningConfiguration>' > $tmp.versioning.enabled.xml

echo '<VersioningConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
   <Status>Suspended</Status>
</VersioningConfiguration>' > $tmp.versioning.suspended.xml

S3USER=tester

_s3_put /bucket
_s3_put /bucket?versioning -T $tmp.versioning.enabled.xml
_s3_get /bucket?versioning -D - | _filter_curl xml
_s3_put /bucket?versioning -T $tmp.versioning.suspended.xml
_s3_get /bucket?versioning -D - | _filter_curl xml
