#!/bin/bash
# Copyright(c)2014 NTT corp. All Rights Reserved.
# DB1-1-5-1_10

. ./common

echo '<VersioningConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
   <Status>Enabled</Status>
</VersioningConfiguration>' > $tmp.versioning.xml

S3USER=tester

_s3_put /bucket
_s3_put /bucket?versioning -T $tmp.versioning.xml -H "x-amz-mfa: 12345" -D - | _filter_curl xml
_s3_get /bucket?versioning -D - | _filter_curl xml
