#!/bin/bash
# Copyright(c)2014 NTT corp. All Rights Reserved.
# DB1-1-5-3_3

. ./common

S3USER=tester

_sw_put /a+b
_sw_put /a*b
_s3_get /a+b?versions -D - | _filter_curl xml
_s3_get /a*b?versions -D - | _filter_curl xml

