#!/bin/bash
# Copyright(c)2014 NTT corp. All Rights Reserved.
# DB1-1-1-3

. ./common

S3USER=tester

_s3_put /hoge

echo data > $tmp.data
MD5=$(_md5 $tmp.data) CONTENT_TYPE='application/octet-stream' \
    _s3_put /hoge/a -T $tmp.data \
    -H 'Content-Disposition: attachment; filename="a.txt.gz"' \
    -H 'Content-Encoding: gzip' \
    -H "Content-Length: $(_file_size $tmp.data)" \
    -H 'x-amz-storage-class: STANDARD' -D - | _filter_curl

_s3_get /hoge/a -D - | _filter_curl
