#!/bin/bash
# Copyright(c)2014 NTT corp. All Rights Reserved.
# DB1-1-2-6_2

. ./common

S3USER=tester

_s3_put /bucket
echo data > $tmp.data
MD5=$(_md5 $tmp.data) CONTENT_TYPE='application/octet-stream' \
    _s3_put /bucket/object -T $tmp.data \
    -H 'Content-Disposition: attachment; filename="a.txt.gz"' \
    -H 'Content-Encoding: gzip' \
    -H "Content-Length: $(_file_size $tmp.data)" \
    -H 'x-amz-acl: private' -D - | _filter_curl

_s3_get /bucket/object?acl -D - | _filter_curl xml

_s3_put /bucket/object?acl -H "x-amz-grant-full-control: id='${TENANT}:${TESTER2_USER}',uri='http://acs.amazonaws.com/groups/global/AuthenticatedUsers',uri='http://acs.amazonaws.com/groups/global/AllUsers',uri='http://acs.amazonaws.com/groups/s3/LogDelivery'"
_s3_get /bucket/object?acl -D - | _filter_curl xml
