#!/bin/bash
# Copyright(c)2014 NTT corp. All Rights Reserved.
# DB1-1-2-4_17

. ./common

S3USER=tester

_s3_put /bucket

echo data > $tmp.data
MD5=$(_md5 $tmp.data) CONTENT_TYPE='application/octet-stream' \
    _s3_put /bucket/object -T $tmp.data \
    -H 'Content-Disposition: attachment; filename="a.txt.gz"' \
    -H 'Content-Encoding: gzip' \
    -H "Content-Length: $(_file_size $tmp.data)" \
    -H 'x-amz-acl: private' -D - | _filter_curl

_s3_put /bucket/object?acl -H "x-amz-grant-write-acp: id='${TENANT}:${TESTER_USER},id='${TENANT}:${TESTER2_USER}'"
_s3_get /bucket/object?acl -D - | _filter_curl xml

S3USER=tester2
_s3_get /bucket/object?acl -D - | _filter_curl xml

S3USER=tester

_s3_put /bucket/object?acl -H "x-amz-grant-full-control: id='${TENANT}:${TESTER_USER},id='${TENANT}:${TESTER2_USER}'"
_s3_get /bucket/object?acl -D - | _filter_curl xml

S3USER=tester2

_s3_get /bucket/object?acl -D - | _filter_curl xml
