#!/bin/bash
# Copyright(c)2014 NTT corp. All Rights Reserved.
# DB1-1-8-1_4

. ./common

S3USER=tester

_s3_put /bucket

upload_id=$(_s3_post /bucket/obj_cache_control?uploads \
    -H "Cache-Control: no-cache" | \
    _xpath '/InitiateMultipartUploadResult/UploadId/text()')

_s3_delete /bucket/obj_cache_control?uploadId=${upload_id}

upload_id=$(_s3_post /bucket/obj_expires?uploads \
    -H "Expires: Wed, 15 Apr 2015 20:00:00 GMT" | \
    _xpath '/InitiateMultipartUploadResult/UploadId/text()')

_s3_delete /bucket/obj_expires?uploadId=${upload_id}


_s3_post /bucket/obj_x-amz-server-side-encryption?uploads \
    -H "x-amz-server-side-encryption: AES256" | _filter_curl xml

_s3_post /bucket/obj_x-amz-website-redirect-location?uploads \
    -H "x-amz-website-redirect-location: http://example.com/" | \
    _filter_curl xml


upload_id=$(_s3_post /bucket/obj_x-amz-grant-write?uploads \
    -H 'x-amz-grant-write: id="handa:handa2"' | \
    _xpath '/InitiateMultipartUploadResult/UploadId/text()')

_s3_delete /bucket/obj_x-amz-grant-write?uploadId=${upload_id}
