#!/bin/bash
# Copyright(c)2014 NTT corp. All Rights Reserved.
# DB1-1-8-4_2

. ./common

num=10

S3USER=tester

_s3_put /bucket

upload_id=$(_s3_post /bucket/object?uploads \
    -H "x-amz-acl: public-read-write" \
    -H "x-amz-meta-hoge1: 1" \
    -H "x-amz-meta-hoge2: 2" \
    -H "x-amz-meta-hoge3: 3" | \
    _xpath '/InitiateMultipartUploadResult/UploadId/text()')

echo '<CompleteMultipartUpload>' > $tmp.complete.xml

for i in `seq $num`; do
    _random | dd of=$tmp.data bs=4k seek=1024 count=1 > /dev/null 2>&1

    echo "<Part>
<PartNumber>$i</PartNumber>
<ETag>$(_etag $tmp.data)</ETag>
</Part>" >> $tmp.complete.xml

    _s3_put /bucket/object?uploadId=${upload_id}\&partNumber=$i -T $tmp.data
done

echo '</CompleteMultipartUpload>' >> $tmp.complete.xml

_s3_post /bucket/object?uploadId=hoge -T $tmp.complete.xml -D - | \
    _filter_curl xml

_s3_head /bucket/object | _filter_curl

