#!/bin/bash
# Copyright(c)2014 NTT corp. All Rights Reserved.
# DB1-1-8-4_4

. ./common

num=1

S3USER=tester

_s3_put /bucket

upload_id=$(_s3_post /bucket/object?uploads \
    -H "x-amz-acl: public-read-write" \
    -H "x-amz-meta-hoge1: 1" \
    -H "x-amz-meta-hoge2: 2" \
    -H "x-amz-meta-hoge3: 3" | \
    _xpath '/InitiateMultipartUploadResult/UploadId/text()')

echo '<CompleteMultipartUpload>' > $tmp.no_part.xml
echo '<CompleteMultipartUpload>' > $tmp.no_etag.xml

for i in `seq $num`; do
    _random | dd of=$tmp.data bs=4k seek=1024 count=1 > /dev/null 2>&1

    echo "<Part><ETag>$(_etag $tmp.data)</ETag></Part>" >> $tmp.no_part.xml
    echo "<Part><PartNumber>$i</PartNumber></Part>" >> $tmp.no_etag.xml

    _s3_put /bucket/object?uploadId=${upload_id}\&partNumber=$i -T $tmp.data
done

echo '</CompleteMultipartUpload>' >> $tmp.no_part.xml
echo '</CompleteMultipartUpload>' >> $tmp.no_etag.xml

_s3_post /bucket/object?uploadId=${upload_id} -T $tmp.no_part.xml -D - | \
    _filter_curl xml

_s3_head /bucket/object | _filter_curl


_s3_post /bucket/object?uploadId=${upload_id} -T $tmp.no_etag.xml -D - | \
    _filter_curl xml

_s3_head /bucket/object | _filter_curl
