#!/bin/bash
# Copyright(c)2014 NTT corp. All Rights Reserved.
# DB1-1-8-7_2

. ./common


S3USER=tester

_s3_put /155

upload_id=$(_s3_post /155/%e3%81%82%2etxt?uploads _xq /InitiateMultipartUploadResult/UploadId)
upload_id=$(_s3_post /155/%e3%81%84%2etxt?uploads _xq /InitiateMultipartUploadResult/UploadId)
upload_id=$(_s3_post /155/object?uploads _xq /InitiateMultipartUploadResult/UploadId)


_s3_get /155?uploads\&encoding-type=url\&max-uploads=2 -D - | _filter_curl xml

