#!/bin/bash
# Copyright(c)2014 NTT corp. All Rights Reserved.
# DB1-1-4-3_2

. ./common
S3USER=tester

echo '<CREATEBUCKETCONFIGURATION xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
<LocationConstraint>US</LocationConstraint>
</CREATEBUCKETCONFIGURATION >' > $tmp.xml
_s3_put /bucket -T $tmp.xml -D - | _filter_curl xml
_s3_get /bucket -D - | _filter_curl xml

echo '<CreateBucketConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
<LOCATIONCONSTRAINT>US</LOCATIONCONSTRAINT>
</CreateBucketConfiguration >' > $tmp.xml
_s3_put /bucket2 -T $tmp.xml -D - | _filter_curl xml
_s3_get /bucket2 -D - | _filter_curl xml

echo '<CreateBucketConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
<LocationConstraint>US</LocationConstraint>
<LocationConstraint>US</LocationConstraint>
</CreateBucketConfiguration >' > $tmp.xml
_s3_put /bucket3 -T $tmp.xml -D - | _filter_curl xml
_s3_get /bucket3 -D - | _filter_curl xml
