#!/bin/bash
# Copyright(c)2014 NTT corp. All Rights Reserved.
# DB1-1-4-3_5

. ./common
S3USER=tester

echo '<CreateBucketConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
<LocationConstraint></LocationConstraint>
</CreateBucketConfiguration >' > $tmp.xml

_s3_put /bucket -T $tmp.xml -D - | _filter_curl xml
_s3_get /bucket -D - | _filter_curl xml
